### PR TITLE
Release

### PR DESCRIPTION
**Pull request by tiberiuichim**

### CODE REVIEW

**Comment by wesleybl** [comment]
@avoinea  was it the lint causing Jenkins to complain? The log in PR didn't help much :smile: 

Please wait a while before generating a release. There's another problem I want to fix.

**Review by avoinea — APPROVED** [review]

**Comment by avoinea** [comment]
@wesleybl Ok, I converted this PR to draft. Let us know when ready :wink:

**Comment by wesleybl** [comment]
@avoinea I open #62

**Comment by wesleybl** [comment]
@avoinea shouldn't the lint problem be indicated in PR #59? It indicated no error.

**Pull request merged**
